language: ruby
rvm:
  - 2.3.0

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - AWS_ACCESS_KEY_ID="TEST"
  - AWS_SECRET_ACCESS_KEY="TEST"
  - REGION="MORDOR"
